// The wire protocol, shared by the phone, the server and the desktop agent.
//
// This package exists so that the three surfaces cannot drift apart: they all
// parse with the same schemas, and a change here breaks every consumer's tests
// at once rather than silently in production. Per CLAUDE.md, changing this
// package requires updating docs/SPEC.md in the same commit.

import { z } from 'zod';

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

/** UUIDv7 is generated by the CLIENT so a retried upload is idempotent.
 *  Time-ordered, so blobs sort by capture time without a separate field. */
export const Uuid = z.string().uuid();

/** 32 raw bytes, base64url. Both Ed25519 and X25519 public keys are this size. */
export const PublicKey = z
  .string()
  .regex(/^[A-Za-z0-9_-]{43}$/, 'expected 32 bytes as unpadded base64url');

export const Base64 = z.string().regex(/^[A-Za-z0-9+/]*={0,2}$/, 'expected base64');

export const DeviceRole = z.enum(['phone', 'pc']);

// ---------------------------------------------------------------------------
// Limits
//
// These are protocol facts, not server preferences: the phone must know them to
// avoid uploading something that will be rejected, and the server must enforce
// them because it cannot trust the phone.
// ---------------------------------------------------------------------------

export const LIMITS = {
  /** A prepped page is a few hundred KB. 12 MB leaves generous headroom for a
   *  full resolution original while still bounding a hostile upload. */
  maxBlobBytes: 12 * 1024 * 1024,
  /** Decision 14. */
  maxBytesPerDevice: 2 * 1024 * 1024 * 1024,
  /** Decision 14. */
  retentionDays: 30,
  /** Signatures older than this are refused, so a captured request cannot be
   *  replayed later. */
  signatureSkewSeconds: 300,
  maxPagesPerSession: 100,
} as const;

// ---------------------------------------------------------------------------
// Pairing (decision 5)
//
// The desktop registers first using a join token printed by the VPS bootstrap.
// It then mints a short-lived pairing token, renders it as a QR code, and the
// phone posts its public key with that token. The pairing exchange IS the key
// exchange: the phone receives the desktop's X25519 public key and from then on
// seals every blob to it.
// ---------------------------------------------------------------------------

export const RegisterPcRequest = z.object({
  joinToken: z.string().min(16),
  ed25519PublicKey: PublicKey,
  x25519PublicKey: PublicKey,
  label: z.string().min(1).max(64),
});

export const RegisterPcResponse = z.object({
  accountId: Uuid,
  deviceId: Uuid,
  /** True when this identity key was already registered and the existing device
   *  was returned. That is a desktop restored from its recovery phrase, or a
   *  second desktop set up with the same phrase, rather than a new account. */
  restored: z.boolean(),
});

export const CreatePairingRequest = z.object({
  ttlSeconds: z.number().int().min(30).max(900).default(300),
});

export const CreatePairingResponse = z.object({
  pairingToken: z.string().min(16),
  expiresAt: z.string().datetime(),
  /** Everything the phone needs, so the QR payload is this object as JSON. */
  serverUrl: z.string().url(),
  x25519PublicKey: PublicKey,
});

export const CompletePairingRequest = z.object({
  pairingToken: z.string().min(16),
  ed25519PublicKey: PublicKey,
  label: z.string().min(1).max(64),
});

export const CompletePairingResponse = z.object({
  accountId: Uuid,
  deviceId: Uuid,
  /** The key the phone seals blobs to. */
  x25519PublicKey: PublicKey,
});

// ---------------------------------------------------------------------------
// Blobs
// ---------------------------------------------------------------------------

/** Travels in the clear because the server needs it to group and bill.
 *  Deliberately carries NOTHING about the note's content. */
export const BlobMeta = z.object({
  blobId: Uuid,
  /** Groups pages into one note. Decision 9. */
  sessionId: Uuid,
  /** Page order within the session, 0-based. */
  seq: z.number().int().min(0).max(LIMITS.maxPagesPerSession - 1),
  sizeBytes: z.number().int().min(1).max(LIMITS.maxBlobBytes),
  capturedAt: z.string().datetime(),
});

export const UploadBlobRequest = BlobMeta.extend({
  /** Sealed to the desktop's X25519 key. The server never opens this. */
  ciphertext: Base64,
});

export const UploadBlobResponse = z.object({
  blobId: Uuid,
  /** True when this blobId was already stored, so a retry is a no-op. */
  duplicate: z.boolean(),
});

export const PendingBlobsResponse = z.object({
  blobs: z.array(BlobMeta),
  /** So the phone can warn before it is refused. */
  bytesUsed: z.number().int().min(0),
  bytesQuota: z.number().int().min(0),
});

export const DownloadBlobResponse = BlobMeta.extend({
  ciphertext: Base64,
});

export const AckBlobsRequest = z.object({
  /** Acked in a batch, because a note is many pages and a partial ack would
   *  leave the session half-delivered. */
  blobIds: z.array(Uuid).min(1).max(LIMITS.maxPagesPerSession),
});

export const AckBlobsResponse = z.object({
  deleted: z.number().int().min(0),
});

// ---------------------------------------------------------------------------
// Health
// ---------------------------------------------------------------------------

export const HealthResponse = z.object({
  ok: z.literal(true),
  version: z.string(),
  devices: z.number().int().min(0),
  pendingBlobs: z.number().int().min(0),
});

export const ErrorResponse = z.object({
  error: z.string(),
  message: z.string(),
});

// ---------------------------------------------------------------------------
// Signed request envelope (decision 5)
//
// Every authenticated request carries these headers. The signature covers the
// method, path, timestamp and a hash of the body, so a captured request cannot
// be replayed against a different route or with different content.
// ---------------------------------------------------------------------------

export const AUTH_HEADERS = {
  deviceId: 'x-inkpipe-device',
  timestamp: 'x-inkpipe-timestamp',
  signature: 'x-inkpipe-signature',
} as const;

/** The exact bytes that get signed. Both sides MUST build this identically, so
 *  it lives here rather than being duplicated in client and server. */
export function signingString(parts: {
  method: string;
  path: string;
  timestamp: string;
  bodySha256Hex: string;
}): string {
  return [
    parts.method.toUpperCase(),
    parts.path,
    parts.timestamp,
    parts.bodySha256Hex,
  ].join('\n');
}

export type BlobMeta = z.infer<typeof BlobMeta>;
export type UploadBlobRequest = z.infer<typeof UploadBlobRequest>;
export type PendingBlobsResponse = z.infer<typeof PendingBlobsResponse>;
export type CompletePairingResponse = z.infer<typeof CompletePairingResponse>;
export type DeviceRole = z.infer<typeof DeviceRole>;
